ci: retry release
0s
Run actions/create-release@v1
with:
tag_name: v0.0.4
release_name: Release v0.0.4
body: Release v0.0.4

Changes in this release:

Version updated to 0.0.4

draft: false
prerelease: false

env:
GITHUB_TOKEN: ***
Error: Resource not accessible by integration